//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_TD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int MaPhanHoi { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public string NhanXet { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
